### ISSUE TITLE
Bullet lists render smaller

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh.computer#154]
The text of bullet point lists is smaller than the surrounding paragraphs.

![Uploading 2024-07-08_13-07.png…]()

**Comment by dignifiedquire** [comment]
upload failed

**Comment by flub** [comment]
![2024-07-08_13-07](https://github.com/n0-computer/iroh.computer/assets/146720/cd8e4633-0828-4c94-8083-a33ac9ffc611)
