### ISSUE TITLE
ticket inspector should trim input

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh.computer#206]
<img width="1264" alt="image" src="https://github.com/user-attachments/assets/a3a296df-e4c6-45a4-88c7-d8412025c54f">

Valid ticket is rejected because of trailing whitespace...

**Comment by matheus23** [comment]
@divagant-martian technically this is the wrong repo, it should've been transferred to https://github.com/n0-computer/ticket.iroh.computer/, but I don't actually have the rights to move it there :)

Anyways. This is done as of https://github.com/n0-computer/ticket.iroh.computer/pull/4
