### ISSUE TITLE
first pass fixes

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh.computer#41]
# questions
## doc set

using the `doc set foo bar` command:
The docs say it should look like this:
```
author:fhu3uk4w… doc:x5qffedi…
> doc set foo bar
@fhu3uk4w…: foo = 6lujp3wx… (3 B)
```

But my local output was this:
```
author:4kw4k2ar… doc:z665xcma…
> doc set foo bar
bafkr4ihs5cl65v6sa3gykxkecwmpuuq2xr22vfuvh2l4amgjmewdbqjjhu
```

Is it supposed to look like the former? In which case that is a bug. Otherwise,
I can update the documentation to match the later.

# TODO:

## unfinished sentences
- docs/layers/documents
~"Applications are encouraged"~
~"Any peer can then"~
"In iroh, the thing that links is the thing that syncs. Documents link together files"

## broken images
- ~docs/layers/blobs~

## references aren't linked
- docs/layers/blobs
    the references in the writing aren't hot linked to the references at the
    bottom of the page

## dead links:
- ~`doc new` -> https://iroh.computer/docs/commands/doc-new~

## empty examples
-  [x] `doc join` 
-  [x] `doc list` 
-  [x] `doc share` 
-  [x] `doc get`
- [x] `doc keys`
- [x] `author switch`
- [x] `author list`
- [x] `author new` 
- [x] `blob add`
- `blob share`
- [x] `blob list blobs` -> says blob list collections rn

**Comment by b5** [comment]
closing as complete!
