### ISSUE TITLE
SDK links broken

### ISSUE THREAD

**Issue by Arqu** [n0-computer/iroh.computer#63]
![Screenshot 2023-10-06 at 13 04 10](https://github.com/n0-computer/iroh.computer/assets/1760977/13affe81-564b-4c0d-b0c0-44af5c70d597)

https://iroh.computer/docs/sdks
These two are linking to non existing repos while swift links to `iroh-ffi` (yet both `go` an `python`) also live there now.

**Comment by b5** [comment]
fixed by #69
